baseurl = "https://chnsh.me/" # Hostname (and path) to the root.
title = "Chintan Shah" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Chintan Shah" # Author's name.
    info = "MS in Computer Science @ Northeastern" # Author's job title or info.
    description = "Chintan Shah's Personal Website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    # disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = true

    # Custom CSS
    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/chnsh/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/___chintan___/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/chintan-shah-53671799/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
